### ISSUE TITLE
MSS425E separate switches (and USB) on/off?

### ISSUE THREAD

**Issue by gianky69** [vincenzosuraci/hassio_meross_sensor_switch#1] opened 2019-04-07 10:27 UTC
I'm using your custom component in HA, with latest corrections MSS310 V1.0 works with no trouble.
I have also 2 MSS425E power strips.
Is it possible to command every single switch (there are 3) and the USB, not only the full power strip on/off? I've looked in HA dev-state but these don't appear separate...
Thanks a lot!

**Comment by vincenzosuraci** [comment] 2019-04-07 16:25
The Meross IoT library supports mss425e. If I got it correctly, this device contains multiple controllable switches, for power and even for USB. I confirm that it is not supported by the custom component, since it uses the concept of channels. The problem is that I do not own a mss425e device so I cannot do the proper test in Hass to make it work. Unfortunately,  testing is an essential action to make a custom component work properly.

**Comment by vincenzosuraci** [comment] 2019-04-07 16:59
I can make a try in the next weeks, studying the Meross iot api of [Alberto Geniola](https://github.com/albertogeniola/MerossIot). The problem I see is that without owning the device, it is really hard to debug the custom component.

**Comment by vincenzosuraci** [comment] 2019-04-07 20:47
Hi gianky69,
I committed a new version of the custom_component. Even if I do not own a mss425e, studying the Meross IoT apis, I tried to integrate the support to multiple channels. If you can have a try and feedback to me, it would be helpful to close this issue.

Regards,
Vincenzo

**Comment by gianky69** [comment] 2019-04-08 06:11
I'll try it ASAP ;-)

**Comment by gianky69** [comment] 2019-04-08 18:40
I've tried, but it seems not working... No, my mistake, too many versions of files on desktop, installed the wrong one... **IT WORKS!!!**

Just 3 new troubles:

1. the MSS310 V1.0 switch control (only on/off) disappeared
2. the two MSS425E are very slow to update (about 30 seconds), for every command I give (App or HA)
3. the "channel" 4 (USB) is not "listed"

**Comment by vincenzosuraci** [comment] 2019-04-09 06:14
Hi gianky69,
many thanks for your response. 
Point by point:
1) probably your mss310 version (1.0.0) returns 0 channels. I will try to handle it;
2) I will add a configuration parameter to decrease the grace time; now its default value Is 30 seconds;
3) I will add It, didn't know It was not included in the channel list.

VS

**Comment by vincenzosuraci** [comment] 2019-04-09 08:30
Hi gainky69,
I made the needed modifications. Please, feedback to me if this version solved all your issues.
Pay attention to the "scan_interval" config parameter. I added some notes about it.

VS

**Comment by gianky69** [comment] 2019-04-09 17:34
Something wrong, I get 6 separate switches for MSS425E, 1 without _x, 1 with _USB and 4 with _1 (or 2, 3, 4). MSS425E has 1 USB and 3 sockets
Also when I use the iPhone app I see status changing also in HA (I've used 10 seconds time sync), but if I change status of one switch  the lightning icon remain in previous state and from HA i get an error message:

> 'GenericPlug' object has no attribute 'device'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
>     connection.context(msg))
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
>     self._execute_service(handler, service_call))
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
>     await handler.func(service_call)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
>     self._platforms.values(), func, call, service_name
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 314, in entity_service_call
>     future.result()  # pop exception if have
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 328, in _handle_service_platform_call
>     await getattr(entity, func)(**data)
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/meross/switch.py", line 67, in turn_off
>     device.device.turn_off_channel(self.channel)
> AttributeError: 'GenericPlug' object has no attribute 'device'

And no more switch on/off status for MSS310.

Could you please add old versions so I'll do some testing (also in code). Thanks a lot.

PS: HA is 0.91.2

**Comment by vincenzosuraci** [comment] 2019-04-10 00:55
Dear gianky69,
many thanks for your log reporting, it helped to find a typo in File "/config/custom_components/meross/switch.py", line 60. 
I corrected it with the last commit.

VS

**Comment by vincenzosuraci** [comment] 2019-04-10 01:31
Dear gianky69,
reading your comment:
> Something wrong, I get 6 separate switches for MSS425E, 1 without _x, 1 with _USB and 4 with _1 (or 2, 3, 4). MSS425E has 1 USB and 3 sockets

I got that the custom-component discovers 6 switches. Let me call XXX the Meross device id, you should have the following 6 entities:
1. switch.meross_XXX
2. switch.meross_XXX_1
3. switch.meross_XXX_2
4. switch.meross_XXX_3
5. switch.meross_XXX_4
6. switch.meross_XXX_usb

But, MSS425E has only 4 controllable switches: 3 (one for each socket) and 1 (one for all the 4 USB) so, theoretically the custom-component should discover only 4 switches, namely:
1. switch.meross_XXX (for socket n.1)
2. switch.meross_XXX_1 (for socket n.2)
3. switch.meross_XXX_2 (for socket n.3)
4. switch.meross_XXX_usb (for all the USB)

I kindly ask to you to confirm if I got it correctly, so that I can further investigate the merioss_iot api to discover why they provide me back so many channels (6 instead of 4).

Regards,
Vincenzo

P.S.: meanwhile, try the latest committed version and provide me a feedback, it should have solved some synch problems.

**Comment by vincenzosuraci** [comment] 2019-04-10 01:44
Dear gianky69,
I read the code of meross_iot library and discovered that the USB channel is already counted when I query the total number of channel to the library. So, in the latest committed version of the custom component, you should see one switch less. 

Let me know what do you get with this version of the commit. Sorry for all these requests of feedback, but I do not have your equipment and I just applying for try-and-error.

VS

**Comment by gianky69** [comment] 2019-04-10 07:22
With latest version I get all switches/sockets correctly, as

1. switch.meross_XXX (for all multisocket switch on/off )
2. switch.meross_XXX_1 (for socket n.1)
3. switch.meross_XXX_2 (for socket n.2)
4. switch.meross_XXX_3 (for socket n.3)
5. switch.meross_XXX_usb (for all the USB)

Also MSS310 is now working.

There is another problem to solve: if I change status for one of the switches/sockets from Meross App (iPhone), the status never update in HA (I have waited for more than 2 hours).

**Comment by vincenzosuraci** [comment] 2019-04-10 07:52
Dear gianky69,
many thanks for your swift response.

At current state, we have that the list of switches is correctly reported and each single switch in HA works.

The new issue occurs when with another controller (e.g. the Meross App) you play with the switch, but the current status of the Meross devices is not updated in HA.

This issue is related to a synchronization problem and need more investigation by my side to be solved.

As soon as I come up with a solution I'll reply to you.

VS

**Comment by gianky69** [comment] 2019-04-10 08:01
Thanks a lot, you're doing a very good job!

**Comment by gianky69** [comment] 2019-04-10 13:50
Also MSS310 doesn't update status (nor A, W, V) if switched on (or off) from App or Google Home.
Also no more reading from A, W, V of switched using HA 😢

**Comment by vincenzosuraci** [comment] 2019-04-10 15:17
Dear gainky69,
Regarding:
> Also MSS310 doesn't update status (nor A, W, V) if switched on (or off) from App or Google Home.
Also no more reading from A, W, V of switched using HA

I'm on it. The issue of not updating the status (on/off, A, W, V) is under my investigation.
I'll keep updated. I guess I'll need some days (I do it in my spare time).
VS

**Comment by vincenzosuraci** [comment] 2019-04-10 18:32
Dear gianky69,
I re-organized a bit the code and did some tests, reducing the scan_interval to 5 seconds. I still have to perform some long lasting tests (e.g. days). It seems to work now, but please, check you too the new version of the code and feedback to me.

I have a possible candidate reason to explain why sometimes the synch between HA and the Mersso cloud stops and it relies on the possibility that the under-lying meross_iot library stop working and need to be reset...

VS

**Comment by gianky69** [comment] 2019-04-10 20:18
I'm going to test it. Now it seems updating and V, A, W working again. See next days...

**Comment by vincenzosuraci** [comment] 2019-04-11 06:45
I confirm that randomly the Meross iot library fails to connect to the Meross Cloud and stops sending updated status info. While switching still works. With version 2.0.0 the meross iot library has implemented a multi-thread asynch communication with the Meross Cloud. Probably if it fails once to connect to the Cloud, It stops updating the info, but without printing errors. I still need to find out a solution...

**Comment by gianky69** [comment] 2019-04-11 07:06
Have you talk about this with Alberto Geniola?

**Comment by vincenzosuraci** [comment] 2019-04-11 07:39
Right now: [https://github.com/albertogeniola/MerossIot/issues/28](https://github.com/albertogeniola/MerossIot/issues/28)

**Comment by gianky69** [comment] 2019-04-12 06:58
I've updated the __init.py__ in custom_components/meross as Alberto Geniola wrote, changing REQUIREMENTS = ['meross_iot==0.2.0.0'] to ['meross_iot==0.2.0.1'].
Restarted HA all seems ok, but let's wait some minutes, hours, days... (fingercrossed)

UPDATE:
After some hours it seems hanging.
The merossiot seems updated (in config/deps/lib/phyton3.7/site-packages/ I find 2 folders - meross_iot and meross_iot-0.2.0.1.dist-info).
Using APP or GoogleHome the status doesn't change in HA (but switching in HA continues working)

**Comment by vincenzosuraci** [comment] 2019-04-12 18:56
Hi Gianky69,
I'm working on this issue. It Is not that easy, but having some try and error, we will come up with a stable solution.

VS

**Comment by gianky69** [comment] 2019-04-12 19:19
Sure!

**Comment by vincenzosuraci** [comment] 2019-04-13 14:27
Dear gianky69,
I kindly ask to you to download and test the latest version and let me know if it hangs out.

VS

**Comment by gianky69** [comment] 2019-04-14 06:43
Installed, and after a night it continues working.
The latest version seems sometime just a little less responsive to the commands from HA (and to status update in HA if devices changed from App or GA) than before. Could it be or is it my impression? Waiting for long term (some days) check...

**Comment by vincenzosuraci** [comment] 2019-04-14 14:01
Indeed, It is less reactive, since, trying to solve the random hangs, I implemented a full async version. So, as you send a command, it is scheduled in the HA queuing. So, if other tasks are running, a small delay occurs.

I will try to branch a synch version, to see if there is any possibility to improve the performances.

VS

**Comment by vincenzosuraci** [comment] 2019-04-15 07:57
Dear gianky69,
let me know if, after some days, the custom-component still works. The result of m testing is that it is stable, but I would need feedback in case other issues occur. Otherwise, if everything is okay, I would close this issue.

**Comment by gianky69** [comment] 2019-04-15 08:03
2 days gone and still working!

**Comment by vincenzosuraci** [comment] 2019-04-15 09:13
Very good news.

Update to the latest version, since I handled some Exception (due to network failures: e.g. internet down) that can hang HA.

VS

**Comment by gianky69** [comment] 2019-04-16 06:34
A "little new problem": after some time Home Assistant seems not responding (to browser nor to HA iOS App).
But HA is up and running and I can connect via FTP, but I cannot open interface  in browser and there is no response after round spinning. All I can do is power off and on the whole system...
I'm on a (poor) ADSL connection, but all this happens also in LAN...

**Comment by vincenzosuraci** [comment] 2019-04-16 07:09
Dear Gianky69,
first of all, I thank you for the feedback. I'm going to close this issue, to merge it with this one [link](https://github.com/vincenzosuraci/hassio_meross_sensor_switch/issues/5), since the problem we are facing is the reliability over the time of the custom-components.

If is it possible for you, using SSH or Samba or FTP try to get access to the log file (even if the Lovelace UI stops working, Hassio should still work and give you access to the log file).

We are on the way to identify the block of source code that is causing the freeze in case the internet connection is not stable, but I need more investigation.

Since I have a fiber optic connection, I'm not suffering connection timeouts with the Meross cloud server. But, in case it occurs, the custom-componet should not freeze and wait until the connection is established.

Regards,
Vincenzo

**Closed as completed** 2019-04-16 07:09 UTC
